System.config({
  baseURL: "/SPA/forms/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "src/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  map: {
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@2.0.1",
    "aurelia-dialog": "npm:aurelia-dialog@1.0.0-beta.3.0.1",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.1.0",
    "aurelia-framework": "npm:aurelia-framework@1.0.8",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.1.0",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bootstrap": "github:twbs/bootstrap@3.3.7",
    "core-js": "npm:core-js@1.2.7",
    "fetch": "github:github/fetch@2.0.2",
    "font-awesome": "npm:font-awesome@4.7.0",
    "jquery": "npm:jquery@3.1.1",
    "jquery-ui": "npm:jquery-ui@1.12.1",
    "ladda": "npm:ladda@1.0.0",
    "metismenu": "npm:metismenu@2.6.2",
    "microplugin": "npm:microplugin@0.0.3",
    "moment": "npm:moment@2.17.1",
    "selectize": "github:selectize/selectize.js@0.12.6",
    "sifter": "github:brianreavis/sifter.js@0.5.3",
    "sweetalert2": "npm:sweetalert2@6.4.2",
    "text": "github:systemjs/plugin-text@0.0.9",
    "toastr": "npm:toastr@2.1.2",
    "whatwg-fetch": "npm:whatwg-fetch@1.0.0",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.9"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:twbs/bootstrap@3.3.7": {
      "jquery": "npm:jquery@3.1.1"
    },
    "npm:asn1.js@4.9.1": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-binding@1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0"
    },
    "npm:aurelia-bootstrapper@2.0.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.8",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.1.0",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.1.1",
      "aurelia-router": "npm:aurelia-router@1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.3.0",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.2.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.2.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.1"
    },
    "npm:aurelia-dependency-injection@1.3.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-dialog@1.0.0-beta.3.0.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-event-aggregator@1.0.1": {
      "aurelia-logging": "npm:aurelia-logging@1.3.0"
    },
    "npm:aurelia-framework@1.0.8": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-history-browser@1.0.0": {
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-loader-default@1.0.0": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-loader@1.0.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-logging-console@1.0.0": {
      "aurelia-logging": "npm:aurelia-logging@1.3.0"
    },
    "npm:aurelia-metadata@1.0.3": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-pal-browser@1.1.0": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-polyfills@1.1.1": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-route-recognizer@1.1.0": {
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-router@1.1.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.1.0"
    },
    "npm:aurelia-task-queue@1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.3.0"
    },
    "npm:aurelia-templating-binding@1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-templating-resources@1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-templating-router@1.0.1": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-router": "npm:aurelia-router@1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.3.0"
    },
    "npm:aurelia-templating@1.3.0": {
      "aurelia-binding": "npm:aurelia-binding@1.2.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.3.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.3.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.3",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.2.0"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bn.js@4.11.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.3",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.3.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.8",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.3.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.8"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.9",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:elliptic@6.3.3": {
      "bn.js": "npm:bn.js@4.11.6",
      "brorand": "npm:brorand@1.0.7",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:es6-promise@4.1.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:font-awesome@4.7.0": {
      "css": "github:systemjs/plugin-css@0.1.32"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:jquery-ui@1.12.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:ladda@1.0.0": {
      "spin.js": "npm:spin.js@2.3.2"
    },
    "npm:metismenu@2.6.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "brorand": "npm:brorand@1.0.7"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.9.1",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.9",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.9": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:sweetalert2@6.4.2": {
      "es6-promise": "npm:es6-promise@4.1.0"
    },
    "npm:toastr@2.1.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  },
  bundles: {
    "dist/admin-build-b96578c1ca.js": [
      "rrs/admin/home.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/admin/home.js",
      "rrs/admin/index.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/admin/index.js",
      "rrs/admin/login.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/admin/login.js",
      "rrs/admin/restaurants.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/admin/restaurants.js",
      "rrs/admin/users.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/admin/users.js"
    ],
    "dist/restaurant-build-2e589e24c5.js": [
      "rrs/restaurant/account.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/restaurant/account.js",
      "rrs/restaurant/home.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/restaurant/home.js",
      "rrs/restaurant/index.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/restaurant/index.js",
      "rrs/restaurant/login.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/restaurant/login.js",
      "rrs/restaurant/reservations.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/restaurant/reservations.js",
      "rrs/restaurant/signup.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/restaurant/signup.js"
    ],
    "dist/user-build-2b8c32a1ee.js": [
      "rrs/user/account.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/user/account.js",
      "rrs/user/home.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/user/home.js",
      "rrs/user/index.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/user/index.js",
      "rrs/user/login.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/user/login.js",
      "rrs/user/restaurantsResults.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/user/restaurantsResults.js",
      "rrs/user/selectedRestaurant.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/user/selectedRestaurant.js",
      "rrs/user/signup.html!github:systemjs/plugin-text@0.0.9.js",
      "rrs/user/signup.js"
    ],
    "dist/vendor-build-ec1dfa53e9.js": [
      "github:github/fetch@2.0.2.js",
      "github:github/fetch@2.0.2/fetch.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "github:systemjs/plugin-text@0.0.9.js",
      "github:systemjs/plugin-text@0.0.9/text.js",
      "github:twbs/bootstrap@3.3.7.js",
      "github:twbs/bootstrap@3.3.7/js/bootstrap.js",
      "npm:aurelia-binding@1.2.0.js",
      "npm:aurelia-binding@1.2.0/aurelia-binding.js",
      "npm:aurelia-bootstrapper@2.0.1.js",
      "npm:aurelia-bootstrapper@2.0.1/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.3.0.js",
      "npm:aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/ai-dialog-body.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/ai-dialog-footer.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/ai-dialog-header.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/ai-dialog.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/attach-focus.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/aurelia-dialog.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/dialog-configuration.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/dialog-controller.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/dialog-options.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/dialog-renderer.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/dialog-result.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/dialog-service.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/lifecycle.js",
      "npm:aurelia-dialog@1.0.0-beta.3.0.1/renderer.js",
      "npm:aurelia-event-aggregator@1.0.1.js",
      "npm:aurelia-event-aggregator@1.0.1/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.1.0.js",
      "npm:aurelia-fetch-client@1.1.0/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.0.8.js",
      "npm:aurelia-framework@1.0.8/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0.js",
      "npm:aurelia-history-browser@1.0.0/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0.js",
      "npm:aurelia-history@1.0.0/aurelia-history.js",
      "npm:aurelia-loader-default@1.0.0.js",
      "npm:aurelia-loader-default@1.0.0/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0.js",
      "npm:aurelia-loader@1.0.0/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0.js",
      "npm:aurelia-logging-console@1.0.0/aurelia-logging-console.js",
      "npm:aurelia-logging@1.3.0.js",
      "npm:aurelia-logging@1.3.0/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.3.js",
      "npm:aurelia-metadata@1.0.3/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.1.0.js",
      "npm:aurelia-pal-browser@1.1.0/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.3.0.js",
      "npm:aurelia-pal@1.3.0/aurelia-pal.js",
      "npm:aurelia-path@1.1.1.js",
      "npm:aurelia-path@1.1.1/aurelia-path.js",
      "npm:aurelia-polyfills@1.1.1.js",
      "npm:aurelia-polyfills@1.1.1/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.1.0.js",
      "npm:aurelia-route-recognizer@1.1.0/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.1.1.js",
      "npm:aurelia-router@1.1.1/aurelia-router.js",
      "npm:aurelia-task-queue@1.2.0.js",
      "npm:aurelia-task-queue@1.2.0/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.2.0.js",
      "npm:aurelia-templating-binding@1.2.0/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.2.0.js",
      "npm:aurelia-templating-resources@1.2.0/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.2.0/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.2.0/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/attr-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/aurelia-hide-style.js",
      "npm:aurelia-templating-resources@1.2.0/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.2.0/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.2.0/binding-signaler.js",
      "npm:aurelia-templating-resources@1.2.0/compose.js",
      "npm:aurelia-templating-resources@1.2.0/css-resource.js",
      "npm:aurelia-templating-resources@1.2.0/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/dynamic-element.js",
      "npm:aurelia-templating-resources@1.2.0/focus.js",
      "npm:aurelia-templating-resources@1.2.0/hide.js",
      "npm:aurelia-templating-resources@1.2.0/html-resource-plugin.js",
      "npm:aurelia-templating-resources@1.2.0/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.2.0/if.js",
      "npm:aurelia-templating-resources@1.2.0/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.2.0/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.2.0/repeat.js",
      "npm:aurelia-templating-resources@1.2.0/replaceable.js",
      "npm:aurelia-templating-resources@1.2.0/sanitize-html.js",
      "npm:aurelia-templating-resources@1.2.0/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/show.js",
      "npm:aurelia-templating-resources@1.2.0/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/with.js",
      "npm:aurelia-templating-router@1.0.1.js",
      "npm:aurelia-templating-router@1.0.1/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.1/route-href.js",
      "npm:aurelia-templating-router@1.0.1/route-loader.js",
      "npm:aurelia-templating-router@1.0.1/router-view.js",
      "npm:aurelia-templating@1.3.0.js",
      "npm:aurelia-templating@1.3.0/aurelia-templating.js",
      "npm:babel-core@5.8.38.js",
      "npm:babel-core@5.8.38/browser.js",
      "npm:babel-runtime@5.8.38/core-js/object/define-property.js",
      "npm:babel-runtime@5.8.38/core-js/promise.js",
      "npm:babel-runtime@5.8.38/helpers/class-call-check.js",
      "npm:babel-runtime@5.8.38/helpers/create-class.js",
      "npm:babel-runtime@5.8.38/helpers/create-decorated-class.js",
      "npm:babel-runtime@5.8.38/helpers/define-decorated-property-descriptor.js",
      "npm:core-js@1.2.7.js",
      "npm:core-js@1.2.7/index.js",
      "npm:core-js@1.2.7/library/fn/object/define-property.js",
      "npm:core-js@1.2.7/library/fn/promise.js",
      "npm:core-js@1.2.7/library/modules/$.a-function.js",
      "npm:core-js@1.2.7/library/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.7/library/modules/$.an-object.js",
      "npm:core-js@1.2.7/library/modules/$.classof.js",
      "npm:core-js@1.2.7/library/modules/$.cof.js",
      "npm:core-js@1.2.7/library/modules/$.core.js",
      "npm:core-js@1.2.7/library/modules/$.ctx.js",
      "npm:core-js@1.2.7/library/modules/$.defined.js",
      "npm:core-js@1.2.7/library/modules/$.descriptors.js",
      "npm:core-js@1.2.7/library/modules/$.dom-create.js",
      "npm:core-js@1.2.7/library/modules/$.export.js",
      "npm:core-js@1.2.7/library/modules/$.fails.js",
      "npm:core-js@1.2.7/library/modules/$.for-of.js",
      "npm:core-js@1.2.7/library/modules/$.global.js",
      "npm:core-js@1.2.7/library/modules/$.has.js",
      "npm:core-js@1.2.7/library/modules/$.hide.js",
      "npm:core-js@1.2.7/library/modules/$.html.js",
      "npm:core-js@1.2.7/library/modules/$.invoke.js",
      "npm:core-js@1.2.7/library/modules/$.iobject.js",
      "npm:core-js@1.2.7/library/modules/$.is-array-iter.js",
      "npm:core-js@1.2.7/library/modules/$.is-object.js",
      "npm:core-js@1.2.7/library/modules/$.iter-call.js",
      "npm:core-js@1.2.7/library/modules/$.iter-create.js",
      "npm:core-js@1.2.7/library/modules/$.iter-define.js",
      "npm:core-js@1.2.7/library/modules/$.iter-detect.js",
      "npm:core-js@1.2.7/library/modules/$.iter-step.js",
      "npm:core-js@1.2.7/library/modules/$.iterators.js",
      "npm:core-js@1.2.7/library/modules/$.js",
      "npm:core-js@1.2.7/library/modules/$.library.js",
      "npm:core-js@1.2.7/library/modules/$.microtask.js",
      "npm:core-js@1.2.7/library/modules/$.property-desc.js",
      "npm:core-js@1.2.7/library/modules/$.redefine-all.js",
      "npm:core-js@1.2.7/library/modules/$.redefine.js",
      "npm:core-js@1.2.7/library/modules/$.same-value.js",
      "npm:core-js@1.2.7/library/modules/$.set-proto.js",
      "npm:core-js@1.2.7/library/modules/$.set-species.js",
      "npm:core-js@1.2.7/library/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.7/library/modules/$.shared.js",
      "npm:core-js@1.2.7/library/modules/$.species-constructor.js",
      "npm:core-js@1.2.7/library/modules/$.strict-new.js",
      "npm:core-js@1.2.7/library/modules/$.string-at.js",
      "npm:core-js@1.2.7/library/modules/$.task.js",
      "npm:core-js@1.2.7/library/modules/$.to-integer.js",
      "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/library/modules/$.to-length.js",
      "npm:core-js@1.2.7/library/modules/$.uid.js",
      "npm:core-js@1.2.7/library/modules/$.wks.js",
      "npm:core-js@1.2.7/library/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.7/library/modules/es6.array.iterator.js",
      "npm:core-js@1.2.7/library/modules/es6.object.to-string.js",
      "npm:core-js@1.2.7/library/modules/es6.promise.js",
      "npm:core-js@1.2.7/library/modules/es6.string.iterator.js",
      "npm:core-js@1.2.7/library/modules/web.dom.iterable.js",
      "npm:core-js@1.2.7/modules/$.a-function.js",
      "npm:core-js@1.2.7/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.7/modules/$.an-object.js",
      "npm:core-js@1.2.7/modules/$.array-copy-within.js",
      "npm:core-js@1.2.7/modules/$.array-fill.js",
      "npm:core-js@1.2.7/modules/$.array-includes.js",
      "npm:core-js@1.2.7/modules/$.array-methods.js",
      "npm:core-js@1.2.7/modules/$.array-species-create.js",
      "npm:core-js@1.2.7/modules/$.classof.js",
      "npm:core-js@1.2.7/modules/$.cof.js",
      "npm:core-js@1.2.7/modules/$.collection-strong.js",
      "npm:core-js@1.2.7/modules/$.collection-to-json.js",
      "npm:core-js@1.2.7/modules/$.collection-weak.js",
      "npm:core-js@1.2.7/modules/$.collection.js",
      "npm:core-js@1.2.7/modules/$.core.js",
      "npm:core-js@1.2.7/modules/$.ctx.js",
      "npm:core-js@1.2.7/modules/$.defined.js",
      "npm:core-js@1.2.7/modules/$.descriptors.js",
      "npm:core-js@1.2.7/modules/$.dom-create.js",
      "npm:core-js@1.2.7/modules/$.enum-keys.js",
      "npm:core-js@1.2.7/modules/$.export.js",
      "npm:core-js@1.2.7/modules/$.fails-is-regexp.js",
      "npm:core-js@1.2.7/modules/$.fails.js",
      "npm:core-js@1.2.7/modules/$.fix-re-wks.js",
      "npm:core-js@1.2.7/modules/$.flags.js",
      "npm:core-js@1.2.7/modules/$.for-of.js",
      "npm:core-js@1.2.7/modules/$.get-names.js",
      "npm:core-js@1.2.7/modules/$.global.js",
      "npm:core-js@1.2.7/modules/$.has.js",
      "npm:core-js@1.2.7/modules/$.hide.js",
      "npm:core-js@1.2.7/modules/$.html.js",
      "npm:core-js@1.2.7/modules/$.invoke.js",
      "npm:core-js@1.2.7/modules/$.iobject.js",
      "npm:core-js@1.2.7/modules/$.is-array-iter.js",
      "npm:core-js@1.2.7/modules/$.is-array.js",
      "npm:core-js@1.2.7/modules/$.is-integer.js",
      "npm:core-js@1.2.7/modules/$.is-object.js",
      "npm:core-js@1.2.7/modules/$.is-regexp.js",
      "npm:core-js@1.2.7/modules/$.iter-call.js",
      "npm:core-js@1.2.7/modules/$.iter-create.js",
      "npm:core-js@1.2.7/modules/$.iter-define.js",
      "npm:core-js@1.2.7/modules/$.iter-detect.js",
      "npm:core-js@1.2.7/modules/$.iter-step.js",
      "npm:core-js@1.2.7/modules/$.iterators.js",
      "npm:core-js@1.2.7/modules/$.js",
      "npm:core-js@1.2.7/modules/$.keyof.js",
      "npm:core-js@1.2.7/modules/$.library.js",
      "npm:core-js@1.2.7/modules/$.math-expm1.js",
      "npm:core-js@1.2.7/modules/$.math-log1p.js",
      "npm:core-js@1.2.7/modules/$.math-sign.js",
      "npm:core-js@1.2.7/modules/$.microtask.js",
      "npm:core-js@1.2.7/modules/$.object-assign.js",
      "npm:core-js@1.2.7/modules/$.object-define.js",
      "npm:core-js@1.2.7/modules/$.object-sap.js",
      "npm:core-js@1.2.7/modules/$.object-to-array.js",
      "npm:core-js@1.2.7/modules/$.own-keys.js",
      "npm:core-js@1.2.7/modules/$.partial.js",
      "npm:core-js@1.2.7/modules/$.path.js",
      "npm:core-js@1.2.7/modules/$.property-desc.js",
      "npm:core-js@1.2.7/modules/$.redefine-all.js",
      "npm:core-js@1.2.7/modules/$.redefine.js",
      "npm:core-js@1.2.7/modules/$.replacer.js",
      "npm:core-js@1.2.7/modules/$.same-value.js",
      "npm:core-js@1.2.7/modules/$.set-proto.js",
      "npm:core-js@1.2.7/modules/$.set-species.js",
      "npm:core-js@1.2.7/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.7/modules/$.shared.js",
      "npm:core-js@1.2.7/modules/$.species-constructor.js",
      "npm:core-js@1.2.7/modules/$.strict-new.js",
      "npm:core-js@1.2.7/modules/$.string-at.js",
      "npm:core-js@1.2.7/modules/$.string-context.js",
      "npm:core-js@1.2.7/modules/$.string-pad.js",
      "npm:core-js@1.2.7/modules/$.string-repeat.js",
      "npm:core-js@1.2.7/modules/$.string-trim.js",
      "npm:core-js@1.2.7/modules/$.task.js",
      "npm:core-js@1.2.7/modules/$.to-index.js",
      "npm:core-js@1.2.7/modules/$.to-integer.js",
      "npm:core-js@1.2.7/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/modules/$.to-length.js",
      "npm:core-js@1.2.7/modules/$.to-object.js",
      "npm:core-js@1.2.7/modules/$.to-primitive.js",
      "npm:core-js@1.2.7/modules/$.uid.js",
      "npm:core-js@1.2.7/modules/$.wks.js",
      "npm:core-js@1.2.7/modules/core.delay.js",
      "npm:core-js@1.2.7/modules/core.dict.js",
      "npm:core-js@1.2.7/modules/core.function.part.js",
      "npm:core-js@1.2.7/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.7/modules/core.get-iterator.js",
      "npm:core-js@1.2.7/modules/core.is-iterable.js",
      "npm:core-js@1.2.7/modules/core.log.js",
      "npm:core-js@1.2.7/modules/core.number.iterator.js",
      "npm:core-js@1.2.7/modules/core.object.classof.js",
      "npm:core-js@1.2.7/modules/core.object.define.js",
      "npm:core-js@1.2.7/modules/core.object.is-object.js",
      "npm:core-js@1.2.7/modules/core.object.make.js",
      "npm:core-js@1.2.7/modules/core.string.escape-html.js",
      "npm:core-js@1.2.7/modules/core.string.unescape-html.js",
      "npm:core-js@1.2.7/modules/es5.js",
      "npm:core-js@1.2.7/modules/es6.array.copy-within.js",
      "npm:core-js@1.2.7/modules/es6.array.fill.js",
      "npm:core-js@1.2.7/modules/es6.array.find-index.js",
      "npm:core-js@1.2.7/modules/es6.array.find.js",
      "npm:core-js@1.2.7/modules/es6.array.from.js",
      "npm:core-js@1.2.7/modules/es6.array.iterator.js",
      "npm:core-js@1.2.7/modules/es6.array.of.js",
      "npm:core-js@1.2.7/modules/es6.array.species.js",
      "npm:core-js@1.2.7/modules/es6.function.has-instance.js",
      "npm:core-js@1.2.7/modules/es6.function.name.js",
      "npm:core-js@1.2.7/modules/es6.map.js",
      "npm:core-js@1.2.7/modules/es6.math.acosh.js",
      "npm:core-js@1.2.7/modules/es6.math.asinh.js",
      "npm:core-js@1.2.7/modules/es6.math.atanh.js",
      "npm:core-js@1.2.7/modules/es6.math.cbrt.js",
      "npm:core-js@1.2.7/modules/es6.math.clz32.js",
      "npm:core-js@1.2.7/modules/es6.math.cosh.js",
      "npm:core-js@1.2.7/modules/es6.math.expm1.js",
      "npm:core-js@1.2.7/modules/es6.math.fround.js",
      "npm:core-js@1.2.7/modules/es6.math.hypot.js",
      "npm:core-js@1.2.7/modules/es6.math.imul.js",
      "npm:core-js@1.2.7/modules/es6.math.log10.js",
      "npm:core-js@1.2.7/modules/es6.math.log1p.js",
      "npm:core-js@1.2.7/modules/es6.math.log2.js",
      "npm:core-js@1.2.7/modules/es6.math.sign.js",
      "npm:core-js@1.2.7/modules/es6.math.sinh.js",
      "npm:core-js@1.2.7/modules/es6.math.tanh.js",
      "npm:core-js@1.2.7/modules/es6.math.trunc.js",
      "npm:core-js@1.2.7/modules/es6.number.constructor.js",
      "npm:core-js@1.2.7/modules/es6.number.epsilon.js",
      "npm:core-js@1.2.7/modules/es6.number.is-finite.js",
      "npm:core-js@1.2.7/modules/es6.number.is-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.is-nan.js",
      "npm:core-js@1.2.7/modules/es6.number.is-safe-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.max-safe-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.min-safe-integer.js",
      "npm:core-js@1.2.7/modules/es6.number.parse-float.js",
      "npm:core-js@1.2.7/modules/es6.number.parse-int.js",
      "npm:core-js@1.2.7/modules/es6.object.assign.js",
      "npm:core-js@1.2.7/modules/es6.object.freeze.js",
      "npm:core-js@1.2.7/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/modules/es6.object.get-own-property-names.js",
      "npm:core-js@1.2.7/modules/es6.object.get-prototype-of.js",
      "npm:core-js@1.2.7/modules/es6.object.is-extensible.js",
      "npm:core-js@1.2.7/modules/es6.object.is-frozen.js",
      "npm:core-js@1.2.7/modules/es6.object.is-sealed.js",
      "npm:core-js@1.2.7/modules/es6.object.is.js",
      "npm:core-js@1.2.7/modules/es6.object.keys.js",
      "npm:core-js@1.2.7/modules/es6.object.prevent-extensions.js",
      "npm:core-js@1.2.7/modules/es6.object.seal.js",
      "npm:core-js@1.2.7/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.7/modules/es6.object.to-string.js",
      "npm:core-js@1.2.7/modules/es6.promise.js",
      "npm:core-js@1.2.7/modules/es6.reflect.apply.js",
      "npm:core-js@1.2.7/modules/es6.reflect.construct.js",
      "npm:core-js@1.2.7/modules/es6.reflect.define-property.js",
      "npm:core-js@1.2.7/modules/es6.reflect.delete-property.js",
      "npm:core-js@1.2.7/modules/es6.reflect.enumerate.js",
      "npm:core-js@1.2.7/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@1.2.7/modules/es6.reflect.get.js",
      "npm:core-js@1.2.7/modules/es6.reflect.has.js",
      "npm:core-js@1.2.7/modules/es6.reflect.is-extensible.js",
      "npm:core-js@1.2.7/modules/es6.reflect.own-keys.js",
      "npm:core-js@1.2.7/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@1.2.7/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@1.2.7/modules/es6.reflect.set.js",
      "npm:core-js@1.2.7/modules/es6.regexp.constructor.js",
      "npm:core-js@1.2.7/modules/es6.regexp.flags.js",
      "npm:core-js@1.2.7/modules/es6.regexp.match.js",
      "npm:core-js@1.2.7/modules/es6.regexp.replace.js",
      "npm:core-js@1.2.7/modules/es6.regexp.search.js",
      "npm:core-js@1.2.7/modules/es6.regexp.split.js",
      "npm:core-js@1.2.7/modules/es6.set.js",
      "npm:core-js@1.2.7/modules/es6.string.code-point-at.js",
      "npm:core-js@1.2.7/modules/es6.string.ends-with.js",
      "npm:core-js@1.2.7/modules/es6.string.from-code-point.js",
      "npm:core-js@1.2.7/modules/es6.string.includes.js",
      "npm:core-js@1.2.7/modules/es6.string.iterator.js",
      "npm:core-js@1.2.7/modules/es6.string.raw.js",
      "npm:core-js@1.2.7/modules/es6.string.repeat.js",
      "npm:core-js@1.2.7/modules/es6.string.starts-with.js",
      "npm:core-js@1.2.7/modules/es6.string.trim.js",
      "npm:core-js@1.2.7/modules/es6.symbol.js",
      "npm:core-js@1.2.7/modules/es6.weak-map.js",
      "npm:core-js@1.2.7/modules/es6.weak-set.js",
      "npm:core-js@1.2.7/modules/es7.array.includes.js",
      "npm:core-js@1.2.7/modules/es7.map.to-json.js",
      "npm:core-js@1.2.7/modules/es7.object.entries.js",
      "npm:core-js@1.2.7/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@1.2.7/modules/es7.object.values.js",
      "npm:core-js@1.2.7/modules/es7.regexp.escape.js",
      "npm:core-js@1.2.7/modules/es7.set.to-json.js",
      "npm:core-js@1.2.7/modules/es7.string.at.js",
      "npm:core-js@1.2.7/modules/es7.string.pad-left.js",
      "npm:core-js@1.2.7/modules/es7.string.pad-right.js",
      "npm:core-js@1.2.7/modules/es7.string.trim-left.js",
      "npm:core-js@1.2.7/modules/es7.string.trim-right.js",
      "npm:core-js@1.2.7/modules/js.array.statics.js",
      "npm:core-js@1.2.7/modules/web.dom.iterable.js",
      "npm:core-js@1.2.7/modules/web.immediate.js",
      "npm:core-js@1.2.7/modules/web.timers.js",
      "npm:core-js@1.2.7/shim.js",
      "npm:font-awesome@4.7.0.js",
      "npm:font-awesome@4.7.0/css/font-awesome.css!github:systemjs/plugin-css@0.1.32.js",
      "npm:jquery-ui@1.12.1.js",
      "npm:jquery-ui@1.12.1/ui/widget.js",
      "npm:jquery@3.1.1.js",
      "npm:jquery@3.1.1/dist/jquery.js",
      "npm:ladda@1.0.0.js",
      "npm:ladda@1.0.0/dist/ladda.min.js",
      "npm:metismenu@2.6.2.js",
      "npm:metismenu@2.6.2/dist/metisMenu.js",
      "npm:moment@2.17.1.js",
      "npm:moment@2.17.1/moment.js",
      "npm:process@0.11.9.js",
      "npm:process@0.11.9/browser.js",
      "npm:spin.js@2.3.2.js",
      "npm:spin.js@2.3.2/spin.js",
      "npm:toastr@2.1.2.js",
      "npm:toastr@2.1.2/toastr.js",
      "npm:whatwg-fetch@1.0.0.js",
      "npm:whatwg-fetch@1.0.0/fetch.js"
    ],
    "dist/app-build-a28199e9e5.js": [
      "app.html!github:systemjs/plugin-text@0.0.9.js",
      "app.js",
      "common/controllers/appController.js",
      "common/resources/config/environment.js",
      "common/resources/config/init.js",
      "common/resources/constants/alertMessages.js",
      "common/resources/constants/commonMessages.js",
      "common/resources/constants/commonNames.js",
      "common/resources/constants/externalSystemCodes.js",
      "common/resources/customElements/controls/cancelButton.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/cancelButton.js",
      "common/resources/customElements/controls/chosenControl.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/chosenControl.js",
      "common/resources/customElements/controls/comments.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/comments.js",
      "common/resources/customElements/controls/datetimePicker.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/datetimePicker.js",
      "common/resources/customElements/controls/password.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/password.js",
      "common/resources/customElements/controls/restaurantName.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/restaurantName.js",
      "common/resources/customElements/controls/selectControl.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/selectControl.js",
      "common/resources/customElements/controls/tooltipInfo.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/tooltipInfo.js",
      "common/resources/customElements/controls/uploadImg.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/uploadImg.js",
      "common/resources/customElements/controls/yesNoButtons.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/controls/yesNoButtons.js",
      "common/resources/customElements/customAttributes/countryPicker.js",
      "common/resources/customElements/customAttributes/currencyPicker.js",
      "common/resources/customElements/customAttributes/datePicker.js",
      "common/resources/customElements/customAttributes/dateTimePicker.js",
      "common/resources/customElements/customAttributes/timePicker.js",
      "common/resources/customElements/dialogs/confirm.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/dialogs/confirm.js",
      "common/resources/customElements/dialogs/imageDialog.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/dialogs/imageDialog.js",
      "common/resources/customElements/dialogs/loading.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/dialogs/loading.js",
      "common/resources/customElements/dialogs/popupDialog.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/dialogs/popupDialog.js",
      "common/resources/customElements/dialogs/urlDialog.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/dialogs/urlDialog.js",
      "common/resources/customElements/navigation/nav-bar-top.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/navigation/nav-bar-top.js",
      "common/resources/customElements/pages/notAuthorized.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/pages/notAuthorized.js",
      "common/resources/customElements/pages/underMaintenance.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/pages/underMaintenance.js",
      "common/resources/customElements/panels/bodytop.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/panels/bodytop.js",
      "common/resources/customElements/panels/footer.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/panels/footer.js",
      "common/resources/customElements/panels/header.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/panels/header.js",
      "common/resources/customElements/panels/searchRestaurant.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/panels/searchRestaurant.js",
      "common/resources/customElements/panels/uploadPictures.html!github:systemjs/plugin-text@0.0.9.js",
      "common/resources/customElements/panels/uploadPictures.js",
      "common/resources/scripts/customLogAppender.js",
      "common/resources/scripts/error.js",
      "common/resources/scripts/formValidator.js",
      "common/resources/scripts/helper.js",
      "common/resources/scripts/json.js",
      "common/resources/scripts/log.js",
      "common/resources/scripts/popup.js",
      "common/resources/scripts/toast.js",
      "common/resources/validation/rules.js",
      "common/resources/valueConverters/arraySanitizer.js",
      "common/resources/valueConverters/blobToUrl.js",
      "common/resources/valueConverters/checkboxToChoice.js",
      "common/resources/valueConverters/dateAndTimeFormat.js",
      "common/resources/valueConverters/dateFormat.js",
      "common/resources/valueConverters/fileListToArray.js",
      "common/resources/valueConverters/htmlSanitizer.js",
      "common/resources/valueConverters/newLine.js",
      "common/resources/valueConverters/stringToIcon.js",
      "common/resources/valueConverters/viewDebugger.js",
      "common/services/md5.js",
      "common/services/serverLog.js",
      "common/services/webServices.js",
      "main.js",
      "model/TablesBook.js",
      "model/ambience.js",
      "model/historyEntry.js",
      "model/restaurant.js",
      "model/restaurantTable.js",
      "model/user.js",
      "model/userBooking.js"
    ]
  }
});