namespace RRS_DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class changeIdType : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.RestaurantAlerts", "Restaurant_Id", "dbo.Restaurants");
            DropForeignKey("dbo.RestaurantManagers", "Restaurant_Id", "dbo.Restaurants");
            DropForeignKey("dbo.RestaurantTables", "Restaurant_Id", "dbo.Restaurants");
            DropForeignKey("dbo.UserBookings", "Restaurant_Id", "dbo.Restaurants");
            DropForeignKey("dbo.UserBookings", "RestaurantTables_Id", "dbo.RestaurantTables");
            DropForeignKey("dbo.UserBookings", "User_Id", "dbo.Users");
            DropForeignKey("dbo.UserFavoriteRestaurnats", "Restaurant_Id", "dbo.Restaurants");
            DropForeignKey("dbo.UserFavoriteRestaurnats", "User_Id", "dbo.Users");
            DropForeignKey("dbo.UserRestaurnatReviews", "Restaurant_Id", "dbo.Restaurants");
            DropForeignKey("dbo.UserRestaurnatReviews", "User_Id", "dbo.Users");
            DropIndex("dbo.RestaurantAlerts", new[] { "Restaurant_Id" });
            DropIndex("dbo.RestaurantManagers", new[] { "Restaurant_Id" });
            DropIndex("dbo.RestaurantTables", new[] { "Restaurant_Id" });
            DropIndex("dbo.UserBookings", new[] { "Restaurant_Id" });
            DropIndex("dbo.UserBookings", new[] { "RestaurantTables_Id" });
            DropIndex("dbo.UserBookings", new[] { "User_Id" });
            DropIndex("dbo.UserFavoriteRestaurnats", new[] { "Restaurant_Id" });
            DropIndex("dbo.UserFavoriteRestaurnats", new[] { "User_Id" });
            DropIndex("dbo.UserRestaurnatReviews", new[] { "Restaurant_Id" });
            DropIndex("dbo.UserRestaurnatReviews", new[] { "User_Id" });
            DropColumn("dbo.RestaurantAlerts", "RestaurantId");
            DropColumn("dbo.RestaurantManagers", "RestaurantId");
            DropColumn("dbo.RestaurantTables", "RestaurantId");
            DropColumn("dbo.UserBookings", "RestaurantId");
            DropColumn("dbo.UserBookings", "RestaurantTablesId");
            DropColumn("dbo.UserBookings", "UserId");
            DropColumn("dbo.UserFavoriteRestaurnats", "RestaurantId");
            DropColumn("dbo.UserFavoriteRestaurnats", "UserId");
            DropColumn("dbo.UserRestaurnatReviews", "RestaurantId");
            DropColumn("dbo.UserRestaurnatReviews", "UserId");
            RenameColumn(table: "dbo.RestaurantAlerts", name: "Restaurant_Id", newName: "RestaurantId");
            RenameColumn(table: "dbo.RestaurantManagers", name: "Restaurant_Id", newName: "RestaurantId");
            RenameColumn(table: "dbo.RestaurantTables", name: "Restaurant_Id", newName: "RestaurantId");
            RenameColumn(table: "dbo.UserBookings", name: "Restaurant_Id", newName: "RestaurantId");
            RenameColumn(table: "dbo.UserBookings", name: "RestaurantTables_Id", newName: "RestaurantTablesId");
            RenameColumn(table: "dbo.UserBookings", name: "User_Id", newName: "UserId");
            RenameColumn(table: "dbo.UserFavoriteRestaurnats", name: "Restaurant_Id", newName: "RestaurantId");
            RenameColumn(table: "dbo.UserFavoriteRestaurnats", name: "User_Id", newName: "UserId");
            RenameColumn(table: "dbo.UserRestaurnatReviews", name: "Restaurant_Id", newName: "RestaurantId");
            RenameColumn(table: "dbo.UserRestaurnatReviews", name: "User_Id", newName: "UserId");
            DropPrimaryKey("dbo.Admins");
            DropPrimaryKey("dbo.RestaurantAlerts");
            DropPrimaryKey("dbo.Restaurants");
            DropPrimaryKey("dbo.RestaurantManagers");
            DropPrimaryKey("dbo.RestaurantTables");
            DropPrimaryKey("dbo.UserBookings");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.UserFavoriteRestaurnats");
            DropPrimaryKey("dbo.UserRestaurnatReviews");
            AlterColumn("dbo.Admins", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantAlerts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantAlerts", "RestaurantId", c => c.Int(nullable: false));
            AlterColumn("dbo.Restaurants", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantManagers", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantManagers", "RestaurantId", c => c.Int(nullable: false));
            AlterColumn("dbo.RestaurantTables", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantTables", "RestaurantId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserBookings", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.UserBookings", "RestaurantId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserBookings", "RestaurantTablesId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserBookings", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Users", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.UserFavoriteRestaurnats", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.UserFavoriteRestaurnats", "RestaurantId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserFavoriteRestaurnats", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserRestaurnatReviews", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.UserRestaurnatReviews", "RestaurantId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserRestaurnatReviews", "UserId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Admins", "Id");
            AddPrimaryKey("dbo.RestaurantAlerts", "Id");
            AddPrimaryKey("dbo.Restaurants", "Id");
            AddPrimaryKey("dbo.RestaurantManagers", "Id");
            AddPrimaryKey("dbo.RestaurantTables", "Id");
            AddPrimaryKey("dbo.UserBookings", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.UserFavoriteRestaurnats", "Id");
            AddPrimaryKey("dbo.UserRestaurnatReviews", "Id");
            CreateIndex("dbo.RestaurantAlerts", "RestaurantId");
            CreateIndex("dbo.RestaurantManagers", "RestaurantId");
            CreateIndex("dbo.RestaurantTables", "RestaurantId");
            CreateIndex("dbo.UserBookings", "RestaurantId");
            CreateIndex("dbo.UserBookings", "RestaurantTablesId");
            CreateIndex("dbo.UserBookings", "UserId");
            CreateIndex("dbo.UserFavoriteRestaurnats", "RestaurantId");
            CreateIndex("dbo.UserFavoriteRestaurnats", "UserId");
            CreateIndex("dbo.UserRestaurnatReviews", "RestaurantId");
            CreateIndex("dbo.UserRestaurnatReviews", "UserId");
            AddForeignKey("dbo.RestaurantAlerts", "RestaurantId", "dbo.Restaurants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RestaurantManagers", "RestaurantId", "dbo.Restaurants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RestaurantTables", "RestaurantId", "dbo.Restaurants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserBookings", "RestaurantId", "dbo.Restaurants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserBookings", "RestaurantTablesId", "dbo.RestaurantTables", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserBookings", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserFavoriteRestaurnats", "RestaurantId", "dbo.Restaurants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserFavoriteRestaurnats", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRestaurnatReviews", "RestaurantId", "dbo.Restaurants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRestaurnatReviews", "UserId", "dbo.Users", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UserRestaurnatReviews", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserRestaurnatReviews", "RestaurantId", "dbo.Restaurants");
            DropForeignKey("dbo.UserFavoriteRestaurnats", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserFavoriteRestaurnats", "RestaurantId", "dbo.Restaurants");
            DropForeignKey("dbo.UserBookings", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserBookings", "RestaurantTablesId", "dbo.RestaurantTables");
            DropForeignKey("dbo.UserBookings", "RestaurantId", "dbo.Restaurants");
            DropForeignKey("dbo.RestaurantTables", "RestaurantId", "dbo.Restaurants");
            DropForeignKey("dbo.RestaurantManagers", "RestaurantId", "dbo.Restaurants");
            DropForeignKey("dbo.RestaurantAlerts", "RestaurantId", "dbo.Restaurants");
            DropIndex("dbo.UserRestaurnatReviews", new[] { "UserId" });
            DropIndex("dbo.UserRestaurnatReviews", new[] { "RestaurantId" });
            DropIndex("dbo.UserFavoriteRestaurnats", new[] { "UserId" });
            DropIndex("dbo.UserFavoriteRestaurnats", new[] { "RestaurantId" });
            DropIndex("dbo.UserBookings", new[] { "UserId" });
            DropIndex("dbo.UserBookings", new[] { "RestaurantTablesId" });
            DropIndex("dbo.UserBookings", new[] { "RestaurantId" });
            DropIndex("dbo.RestaurantTables", new[] { "RestaurantId" });
            DropIndex("dbo.RestaurantManagers", new[] { "RestaurantId" });
            DropIndex("dbo.RestaurantAlerts", new[] { "RestaurantId" });
            DropPrimaryKey("dbo.UserRestaurnatReviews");
            DropPrimaryKey("dbo.UserFavoriteRestaurnats");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.UserBookings");
            DropPrimaryKey("dbo.RestaurantTables");
            DropPrimaryKey("dbo.RestaurantManagers");
            DropPrimaryKey("dbo.Restaurants");
            DropPrimaryKey("dbo.RestaurantAlerts");
            DropPrimaryKey("dbo.Admins");
            AlterColumn("dbo.UserRestaurnatReviews", "UserId", c => c.Long());
            AlterColumn("dbo.UserRestaurnatReviews", "RestaurantId", c => c.Long());
            AlterColumn("dbo.UserRestaurnatReviews", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.UserFavoriteRestaurnats", "UserId", c => c.Long());
            AlterColumn("dbo.UserFavoriteRestaurnats", "RestaurantId", c => c.Long());
            AlterColumn("dbo.UserFavoriteRestaurnats", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Users", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.UserBookings", "UserId", c => c.Long());
            AlterColumn("dbo.UserBookings", "RestaurantTablesId", c => c.Long());
            AlterColumn("dbo.UserBookings", "RestaurantId", c => c.Long());
            AlterColumn("dbo.UserBookings", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantTables", "RestaurantId", c => c.Long());
            AlterColumn("dbo.RestaurantTables", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantManagers", "RestaurantId", c => c.Long());
            AlterColumn("dbo.RestaurantManagers", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Restaurants", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.RestaurantAlerts", "RestaurantId", c => c.Long());
            AlterColumn("dbo.RestaurantAlerts", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Admins", "Id", c => c.Long(nullable: false, identity: true));
            AddPrimaryKey("dbo.UserRestaurnatReviews", "Id");
            AddPrimaryKey("dbo.UserFavoriteRestaurnats", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.UserBookings", "Id");
            AddPrimaryKey("dbo.RestaurantTables", "Id");
            AddPrimaryKey("dbo.RestaurantManagers", "Id");
            AddPrimaryKey("dbo.Restaurants", "Id");
            AddPrimaryKey("dbo.RestaurantAlerts", "Id");
            AddPrimaryKey("dbo.Admins", "Id");
            RenameColumn(table: "dbo.UserRestaurnatReviews", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.UserRestaurnatReviews", name: "RestaurantId", newName: "Restaurant_Id");
            RenameColumn(table: "dbo.UserFavoriteRestaurnats", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.UserFavoriteRestaurnats", name: "RestaurantId", newName: "Restaurant_Id");
            RenameColumn(table: "dbo.UserBookings", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.UserBookings", name: "RestaurantTablesId", newName: "RestaurantTables_Id");
            RenameColumn(table: "dbo.UserBookings", name: "RestaurantId", newName: "Restaurant_Id");
            RenameColumn(table: "dbo.RestaurantTables", name: "RestaurantId", newName: "Restaurant_Id");
            RenameColumn(table: "dbo.RestaurantManagers", name: "RestaurantId", newName: "Restaurant_Id");
            RenameColumn(table: "dbo.RestaurantAlerts", name: "RestaurantId", newName: "Restaurant_Id");
            AddColumn("dbo.UserRestaurnatReviews", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.UserRestaurnatReviews", "RestaurantId", c => c.Int(nullable: false));
            AddColumn("dbo.UserFavoriteRestaurnats", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.UserFavoriteRestaurnats", "RestaurantId", c => c.Int(nullable: false));
            AddColumn("dbo.UserBookings", "UserId", c => c.Int(nullable: false));
            AddColumn("dbo.UserBookings", "RestaurantTablesId", c => c.Int(nullable: false));
            AddColumn("dbo.UserBookings", "RestaurantId", c => c.Int(nullable: false));
            AddColumn("dbo.RestaurantTables", "RestaurantId", c => c.Int(nullable: false));
            AddColumn("dbo.RestaurantManagers", "RestaurantId", c => c.Int(nullable: false));
            AddColumn("dbo.RestaurantAlerts", "RestaurantId", c => c.Int(nullable: false));
            CreateIndex("dbo.UserRestaurnatReviews", "User_Id");
            CreateIndex("dbo.UserRestaurnatReviews", "Restaurant_Id");
            CreateIndex("dbo.UserFavoriteRestaurnats", "User_Id");
            CreateIndex("dbo.UserFavoriteRestaurnats", "Restaurant_Id");
            CreateIndex("dbo.UserBookings", "User_Id");
            CreateIndex("dbo.UserBookings", "RestaurantTables_Id");
            CreateIndex("dbo.UserBookings", "Restaurant_Id");
            CreateIndex("dbo.RestaurantTables", "Restaurant_Id");
            CreateIndex("dbo.RestaurantManagers", "Restaurant_Id");
            CreateIndex("dbo.RestaurantAlerts", "Restaurant_Id");
            AddForeignKey("dbo.UserRestaurnatReviews", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.UserRestaurnatReviews", "Restaurant_Id", "dbo.Restaurants", "Id");
            AddForeignKey("dbo.UserFavoriteRestaurnats", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.UserFavoriteRestaurnats", "Restaurant_Id", "dbo.Restaurants", "Id");
            AddForeignKey("dbo.UserBookings", "User_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.UserBookings", "RestaurantTables_Id", "dbo.RestaurantTables", "Id");
            AddForeignKey("dbo.UserBookings", "Restaurant_Id", "dbo.Restaurants", "Id");
            AddForeignKey("dbo.RestaurantTables", "Restaurant_Id", "dbo.Restaurants", "Id");
            AddForeignKey("dbo.RestaurantManagers", "Restaurant_Id", "dbo.Restaurants", "Id");
            AddForeignKey("dbo.RestaurantAlerts", "Restaurant_Id", "dbo.Restaurants", "Id");
        }
    }
}
