// <auto-generated />
namespace RRS_DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeEnumIToId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeEnumIToId));
        
        string IMigrationMetadata.Id
        {
            get { return "201806202142448_changeEnumIToId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
